language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then ./dependencies.sh; fi
script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./autogen && ./configure && make; fi
branches:
  only:
  - master
env:
  global:
  - LANG="en_US.UTF-8"
