language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
before_install:
- ./dependencies.sh
script:
- ./autogen.sh
cat ./autogen.sh
- ./configure
- make
branches:
  only:
  - master
env:
  global:
  - LANG="en_US.UTF-8"
