language: cpp
dist: trusty
sudo: required

compiler:
  - clang

os:
  - linux

services:
  - docker

script:
  - docker build -t etiam/db .
  - docker run etiam/db /bin/sh -c "cd /home/travis; ./dependencies.sh && ./autogen.sh && ./configure && make"

branches:
  only:
  - master

env:
  global:
  - LANG="en_US.UTF-8"
