language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
      - key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-5.0-dev
before_install:
- echo $LANG
- echo $LC_ALL
llvm-config 
#- sudo apt-cache pkgnames
- ./dependencies.sh
script:
- ./autogen.sh && ./configure && make
branches:
  only:
  - master
env:
  global:
  - LANG="en_US.UTF-8"
